---
version: '3.7'
services:
  schenkexporter:
    image: serotonie/schenkexporter
    ports: 
      - 5000:5000
    environment:
      - TZ=<Continent>/<Town>
      - MYSQL_USER=<user of kimai DB>
      - MYSQL_PASSWORD=<password of kimai DB>
      - MYSQL_HOST=<hostname of kimai DB>
      - MYSQL_DB=<name of kimai DB>
    restart: always